wget -O direct.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
wget -O icloud.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
wget -O apple.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
wget -O Netflix.yaml https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Video/Netflix.yaml
wget -O HBO.yaml https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Video/HBO.yaml
wget -O YouTube.yaml https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/StreamingMedia/Video/YouTube.yaml
wget -O GoogleSearch.yaml https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/Google/GoogleSearch.yaml
wget -O GoogleDrive.yaml https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/Google/GoogleDrive.yaml
wget -O TelegramUS.yaml https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Extra/Telegram/TelegramUS.yaml
wget -O Global.yaml https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Global.yaml
wget -O Unbreak.yaml https://cdn.jsdelivr.net/gh/DivineEngine/Profiles@master/Clash/RuleSet/Unbreak.yaml
wget -O cncidr.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
wget -O lancidr.txt https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt