wget -O reject.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt
wget -O telegramcidr.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt
wget -O applications.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
wget -O google.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt
wget -O direct.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt
wget -O cncidr.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
wget -O proxy.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
wget -O gfw.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
wget -O tld-not-cn.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
wget -O lancidr.txt https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
