services:
  mosdns:
    image: irinesistiana/mosdns:v5.3.3
    container_name: mosdns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./etc:/etc/mosdns
      - ./log:/var/log
    restart: always
