services:
  mihomo:
    image: metacubex/mihomo:latest
    container_name: mihomo
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "7890:7890"
      - "9090:9090"
    volumes:
      - ./config.yaml:/root/.config/mihomo/config.yaml
      - ./ui:/root/.config/mihomo/ui
