version: '3'
services:
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=admin123!
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data:/data